<Project>
  <PropertyGroup>
    <Version>1.0.0-beta.6</Version>
    <Company>Production Reporting</Company>
    <Product>Production Reporting for macOS</Product>
    <Authors>Production Reporting</Authors>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
</Project>
